# 2회차 · NumPy — 데이터를 배열로 다루기

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/KimKangSoo123/Github_Colab_Integration_Practice/blob/main/week2/02_numpy.ipynb)

**오늘의 목표 (약 2.5시간)**
- 왜 NumPy인가 (리스트 vs 배열)
- 배열 생성 · 인덱싱 · 슬라이싱
- 벡터 연산과 브로드캐스팅
- 행렬 연산 기초
- ⭐ 1회차의 정규화 반복문을 **배열 한 줄**로 바꿔보기

**진행 방식**: 개념 → 예제 실행 → 🔧 빈칸 채우기 순서입니다.

*   배열 (Array) 			: 고정된 크기, 연속된 메모리 -> 데이터 조회(검색)에 유리
*   리스트 (List) 			: 가변 크기, 비연속적 메모리 -> 데이터 추가와 삭제에 유리
-----------------------------------------------------------------------------------------------
*   배열 생성 (Array Creation)

    np.array([리스트]) 		: 파이썬 리스트를 넘파이 배열로 바꿉니다.
    
    np.arange(n) 			: 지정한 범위(0, 10, 2 or 0부터 n전까지)의 숫자를 연속된 배열로 만듭니다.
    
    np.zeros(n) / np.ones(n) 	: 0이나 1로 채워진 (n개의 숫자)배열을 만듭니다.

*   인덱싱 (Indexing)

    대괄호 [] 안에 번호를 넣어 특정 위치의 값을 꺼낼 수 있다.
    
    배열의 자리는 왼쪽부터 0번부터 시작하고, -를 쓰면 맨 뒤에서부터 거꾸로 위치를 센다.

*   슬라이싱 (Slicing)

    콜론(:)을 써서 [시작:끝] 형태로 원하는 조각을 잘라낼 수 있다.
    
    시작 번호의 값은 포함하고, 끝 번호의 값 직전까지 가져온다.
-----------------------------------------------------------------------------------------------
*   브로드캐스팅(Broadcasting)

    모양(크기)이 다른 NumPy 배열 간에도 자동으로 크기를 맞춰서 산술 연산을 수행하게 해 주는 기능

---
## 0. 왜 NumPy인가?

머신러닝의 데이터는 사실상 전부 **배열(행렬)** 입니다. 파이썬 기본 리스트로도 계산은 되지만, 데이터가 커지면 느리고 코드도 길어져요. NumPy는 배열 전체를 한 번에, 빠르게 계산합니다.

In [4]:
import numpy as np   # 관례적으로 np 라는 별명으로 불러옵니다

# 리스트를 배열로
scores = np.array([85, 90, 78, 92, 60, 88])
print(scores)
print("타입:", type(scores))
print("모양(shape):", scores.shape)   # (6,) → 원소 6개짜리 1차원

[85 90 78 92 60 88]
타입: <class 'numpy.ndarray'>
모양(shape): (6,)


### 🔧 과제 0-1
아래 리스트를 NumPy 배열로 바꾸고, 그 `shape` 를 출력하세요.

In [5]:
data = [10, 20, 30, 40]

# TODO
arr = np.array(data)
print(arr, arr.shape)

[10 20 30 40] (4,)


---
## 1. 배열 생성

자주 쓰는 생성 함수들입니다.

In [6]:
print(np.zeros(5))          # 0으로 채운 배열
print(np.ones(3))           # 1로 채운 배열
print(np.arange(0, 10, 2))  # 0부터 10 전까지 2씩
print(np.linspace(0, 1, 5)) # 0~1을 5등분

[0. 0. 0. 0. 0.]
[1. 1. 1.]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


---
## 2. 인덱싱 · 슬라이싱

리스트와 비슷하지만 더 강력합니다. 특히 **조건으로 골라내기(불리언 인덱싱)** 가 ML 전처리에서 매우 자주 쓰여요.

In [7]:
scores = np.array([85, 90, 78, 92, 60, 88])

print("첫 원소:", scores[0])
print("앞 3개:", scores[:3])
print("70점 이상만:", scores[scores >= 70])   # 불리언 인덱싱
print("70점 이상 개수:", np.sum(scores >= 70)) # True를 1로 세어줌

첫 원소: 85
앞 3개: [85 90 78]
70점 이상만: [85 90 78 92 88]
70점 이상 개수: 5


### 🔧 과제 2-1
불리언 인덱싱으로 **80점 이상인 점수만** 골라 출력하세요. (1회차에서는 반복문으로 했던 일이에요!)

In [10]:
scores = np.array([85, 90, 78, 92, 60, 88, 45, 73])

# TODO
high = scores[scores >= 80]
print(high)

[85 90 92 88]


---
## 3. 벡터 연산 & 브로드캐스팅

배열끼리, 또는 배열과 숫자를 연산하면 **모든 원소에 한 번에** 적용됩니다. 반복문이 필요 없어요. 이것이 NumPy의 핵심입니다.

In [11]:
scores = np.array([85, 90, 78, 92, 60, 88])

print("모두 +5점:", scores + 5)        # 브로드캐스팅
print("100점 만점 대비 비율:", scores / 100)
print("평균:", scores.mean())
print("표준편차:", scores.std())
print("최대/최소:", scores.max(), scores.min())

모두 +5점: [90 95 83 97 65 93]
100점 만점 대비 비율: [0.85 0.9  0.78 0.92 0.6  0.88]
평균: 82.16666666666667
표준편차: 10.86917149045358
최대/최소: 92 60


### ⭐ 핵심 — 정규화를 한 줄로

1회차에서 반복문으로 짰던 정규화 `(값-최솟값)/(최댓값-최솟값)` 를, NumPy에서는 배열 전체에 한 번에 적용합니다.

In [12]:
scores = np.array([85, 90, 78, 92, 60, 88])

normalized = (scores - scores.min()) / (scores.max() - scores.min())

print("원본:  ", scores)
print("정규화:", np.round(normalized, 3))
# 1회차 반복문 결과와 똑같습니다 — 코드는 한 줄!

원본:   [85 90 78 92 60 88]
정규화: [0.781 0.938 0.562 1.    0.    0.875]


### 🔧 과제 3-1
표준화(standardization)를 한 줄로 구현하세요.
공식: `(값 - 평균) / 표준편차`. 이것도 ML에서 자주 쓰는 스케일링이에요.

In [15]:
scores = np.array([85, 90, 78, 92, 60, 88])

# TODO: mean() 과 std() 를 이용하세요
standardized = (scores - scores.mean() / scores.std())

print(np.round(standardized, 3))
print("평균≈0 확인:", round(float(standardized.mean()), 5))

[77.44 82.44 70.44 84.44 52.44 80.44]
평균≈0 확인: 74.60706


*   round(A, n)함수 		: 숫자(or 변수A)를 지정한 자릿수(n)로 반올림 (출력할 때만 반올림해 보여주는 것)

---
## 4. 2차원 배열 (행렬)

ML 데이터는 보통 **행=샘플, 열=특징** 인 2차원 표입니다. 예: 학생 3명 × 과목 2개.

In [16]:
# 행: 학생, 열: [국어, 영어]
grades = np.array([
    [80, 90],
    [70, 60],
    [95, 85],
])
print("모양:", grades.shape)      # (3, 2)
print("과목별 평균(열 기준):", grades.mean(axis=0))
print("학생별 평균(행 기준):", grades.mean(axis=1))

모양: (3, 2)
과목별 평균(열 기준): [81.66666667 78.33333333]
학생별 평균(행 기준): [85. 65. 90.]


*   “행 방향으로 계산한다” 	: 여러 행에 들어 있는 값을 위아래로 모아서 계산한다는 뜻

*   “열 방향으로 계산한다” 	: 여러 열에 들어 있는 값을 좌우로 모아서 계산한다는 뜻
*   외우는 방법 - axis=0 : 열(동그라미) / axis=1 : 행(작대기)

> 💡 `axis=0` 은 "행을 따라 아래로" = 열별 계산, `axis=1` 은 "열을 따라 옆으로" = 행별 계산. 처음엔 헷갈리니 위 예제를 여러 번 돌려보세요.

### 🔧 오늘의 미니 과제 (제출용)
아래 2차원 배열에서 **(1) 학생별 평균**, **(2) 평균 80점 이상인 학생 수**를 구하세요.

In [17]:
scores2d = np.array([
    [85, 90, 78],
    [60, 55, 70],
    [92, 88, 95],
    [70, 72, 68],
])

# 1) 학생별(행별) 평균
student_means = scores2d.mean(axis=1)          # TODO
print("학생별 평균:", np.round(student_means, 1))

# 2) 평균 80 이상인 학생 수
count = sum(student_means >= 80)                  # TODO (불리언 인덱싱 + sum)
print("우수 학생 수:", count)

학생별 평균: [84.3 61.7 91.7 70. ]
우수 학생 수: 2


---
## 마무리 & 제출

**제출 방법**
1. `런타임 → 모두 실행` 으로 전체를 돌려 결과를 채웁니다.
2. `파일 → GitHub에 사본 저장` → 경로를 `members/본인이름/02_numpy.ipynb` 로 지정합니다.
3. 커밋 메시지: `2회차 완료`

**복습 팁**: 막혔던 셀 아래에 마크다운 셀을 추가해 "왜 헷갈렸는지"를 한두 줄 적어두면 최고의 복습 노트가 됩니다.


**다음 회차 예고 (3회차)**: pandas로 실제 CSV 데이터를 불러오고, matplotlib로 그래프를 그려 데이터를 눈으로 파악합니다.